BWFitness/BWFitness/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.HomePage.as_view(),name='home'),
    path('Exercises/',include('Exercises.urls',namespace='Exercises')),
    path('program/',include('program.urls',namespace='program')),
]

BWFitness/Exercises/urls.py
from django.urls import path
from . import views

app_name = 'Exercises'

urlpatterns=[
     path('',views.ListExercises.as_view(),name='all'),
     path('<slug:slug>/',views.SingleExercise.as_view(),name='single'),
]

BWFitness/program/urls.py
from django.urls import path
from . import views

app_name = 'program'

urlpatterns=[
     path('',views.ProgramList.as_view(),name='my_program'),
     path('add/<slug:slug>/',views.AddToProgram.as_view(),name='add'),
     path('remove/<slug:slug>/',views.RemoveFromProgram.as_view(),name='remove'),
]

BWFitness/Exercises/models.py
from django.db import models
from django.urls import reverse
# Create your models here.

class Exercise(models.Model):
    name = models.CharField(max_length=255,unique=True)
    slug = models.SlugField(allow_unicode=True,null=False,unique=True)
    progressionTo = models.ForeignKey('self',on_delete=models.CASCADE,null=True,blank=True,related_name='harder')
    progressionFrom = models.ForeignKey('self',on_delete=models.CASCADE,null=True,blank=True,related_name='easier')
    difficulty = models.IntegerField()
    link = models.CharField(max_length=255,unique=True,null=True,blank=True)
    plane = models.CharField(max_length=255,null=True,blank=True)
    category = models.CharField(max_length=255,null=True,blank=True)
    description = models.CharField(max_length=500,null=True,blank=True)
    

    def __str__(self):
        return self.name


    def get_absolute_url(self):
        return reverse('single',kwargs={'slug': self.slug})

    class Meta:
        ordering = ['-difficulty','category']

BWFitness/program/models.py
from django.db import models
from Exercises.models import Exercise
# Create your models here.

class Program(models.Model):
    exercise = models.OneToOneField(Exercise,on_delete=models.CASCADE,related_name='part_of_prog')

    def __str__(self):
        return self.exercise.name

    def get_absolute_url(self):
        return reverse('Exercise:single',kwargs={'slug': self.exercise.slug})

BWFitness/Exercises/forms.py
from django import forms

myChoices = (("1","Category"),("2","Difficulty"),("3","Alphabetically"))
class OrderForm(forms.Form):
    # order_field = forms.ChoiceField(choices = myChoices)
    name = forms.CharField(label='Your choice')

BWFitness/BWFitness/views.py
from django.views.generic import TemplateView

class HomePage(TemplateView):
    template_name='index.html'

BWFitness/Exercises/views.py
from django.shortcuts import render
from . import models
from django.views import generic
from . import forms
from program.models import Program
# Create your views here.


class ListExercises(generic.ListView):
    model = models.Exercise

class SingleExercise(generic.DetailView):
    model = models.Exercise

    def get_context_data(self,**kwargs):
        context = super().get_context_data(**kwargs)
        info = Program.objects.all()
        context['ex_list']=[]
        for item in info:
            context['ex_list'].append(item.exercise.name)
        return context

BWFitness/program/views.py
from django.shortcuts import render
from django.views import generic
from .models import Program
from Exercises.models import Exercise
# Create your views here.

class ProgramList(generic.ListView):
    model = Program

class AddToProgram(generic.TemplateView):
    template_name = 'program/add_to_program.html'

    def get_context_data(self,**kwargs):
        context = super().get_context_data(**kwargs)
        myslug = self.kwargs['slug']
        exToAdd = Exercise.objects.get(slug=myslug)
        p = Program(exercise=exToAdd)
        p.save()
        return context


class RemoveFromProgram(generic.TemplateView):
    template_name = 'program/remove_from_program.html'

    def get_context_data(self,**kwargs):
        context = super().get_context_data(**kwargs)
        myslug = self.kwargs['slug']
        exToRemove = Exercise.objects.get(slug=myslug)
        Program.objects.get(exercise=exToRemove).delete()
        return context

BWFitness/Exercises/templates/Exercises/exercise_base.html
{% extends "base.html"%}
{% block content %}
<div class="container">
  <div class="row">
    {% block pre_ex %}{% endblock %}
    {% block ex_content %}{% endblock %}
    {% block post_ex %}{% endblock %}
  </div>
</div>
{% endblock %}

BWFitness/Exercises/templates/Exercises/exercise_detail.html
{% extends 'Exercises/exercise_base.html' %}
{% block ex_content %}
<h1 class='titles'>{{exercise.name}}</h1>
<div class="content">
  <p>{{exercise.description}}</p>
  <p>Category: {{exercise.category}}</p>
  {% if exercise.category != 'Legs' %}
    <p>Plane: {{exercise.plane}}</p>
  {% endif %}
  <a class="btn btn-primary" href="{{exercise.link}}" target="_blank">Video demonstration</a>
  {% if exercise.difficulty < 7 %}
  <br>
    <a class="btn btn-primary" href="{% url 'Exercises:single' slug=exercise.progressionTo.slug %}">Harder Progression</a>
  {% endif %}
  {% if exercise.difficulty > 1 %}
  <br>
    <a class="btn btn-primary" href="{% url 'Exercises:single' slug=exercise.progressionFrom.slug %}">Easier Progression</a>
  {% endif %}
  {% if exercise.name in ex_list %}
    <br>
    <a class="btn btn-danger" href="{% url 'program:remove' slug=exercise.slug %}">Remove From Program</a>
  {% else %}
    <br>
    <a class="btn btn-success" href="{% url 'program:add' slug=exercise.slug %}">Add To Program</a>
  {% endif %}
</div>
{% endblock %}

BWFitness/Exercises/templates/Exercises/exercise_list.html
{% extends 'Exercises/exercise_base.html' %}

{% block ex_content%}
<h1 class='titles'>Chose the exercise you want to learn about</h1>
  <div class="list_group">
    <div class="row">
    {% for ex in object_list %}
    <div class="col-5 listItem">
      <a class='list-ex-item' href="{% url 'Exercises:single' slug=ex.slug %}">
        <h3 class='title'>{{ex.name}}</h3>
      </a>
      <p>Difficulty: {{ex.difficulty}}, Category: {{ex.category}}</p>
    </div>
    {% endfor %}
    </div>
  </div>
{% endblock %}

BWFitness/program/templates/program/add_to_program.html
{% extends "base.html"%}
{% block content%}
<br>
  <p>Added exercise to program</p>
  <a class="btn btn-primary" href="{% url 'Exercises:all'%}">All Exercises</a>
  <a class="btn btn-primary" href="{% url 'program:my_program'%}">Program</a>
  <br>
  <a class="btn btn-primary" href="{% url 'Exercises:single' slug=slug %}">Back To Exercise</a>
{% endblock %}

BWFitness/program/templates/program/program_list.html
{% extends "base.html" %}
{% block content %}
<h1 class='titles'>Your Program</h1>
  <div class="list_group">
    <div class="row">
    {% for item in object_list %}
    <div class="col-5 listItem">
      <a class='list-ex-item' href="{% url 'Exercises:single' slug=item.exercise.slug %}">
        <h3 class='title'>{{item.exercise.name}}</h3>
      </a>
      <p>Difficulty: {{item.exercise.difficulty}}, Category: {{item.exercise.category}}</p>
    </div>
    {% endfor %}
    </div>
  </div>
{% endblock %}

BWFitness/program/templates/program/remove_from_program.html
{% extends "base.html"%}
{% block content%}
<br>
  <p>Removed exercise from program</p>
  <a class="btn btn-primary" href="{% url 'Exercises:all'%}">All Exercises</a>
  <a class="btn btn-primary" href="{% url 'program:my_program'%}">Program</a>
  <br>
  <a class="btn btn-primary" href="{% url 'Exercises:single' slug=slug %}">Back To Exercise</a>
{% endblock %}

BWFitness/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>BWFitness</title>
    <!-- Bootstrap -->
      <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
    <!-- FONT -->
      <link rel="preconnect" href="https://fonts.gstatic.com">
      <link href="https://fonts.googleapis.com/css2?family=Raleway:wght@700&display=swap" rel="stylesheet">
    <!-- Custom CSS -->
      <link rel="stylesheet" href="{% static 'BWFitness/css/master.css' %}">
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="container">
        <a class='navbar-brand' href="{% url 'home' %}">FBFitness</a>
        <a class="nav-link" href="{% url 'Exercises:all' %}">Exercises</a>
        <a class="nav-link" href="{% url 'program:my_program' %}">Program</a>
      </div>
    </nav>
    <div class="container mycontent">
      {% block content %}
      {% endblock %}
    </div>
  </body>
</html>

BWFitness/templates/index.html
{% extends "base.html" %}
{% load static %}
{% block content %}
  <h1 class='titles'>Welcome to BWFitness</h1>
  <p>This is a place where you can learn new body weight exercises you want to unlock! </p>
  <img src="{% static 'BWFitness/images/front_lever.jpg' %}" alt="OOPS, pic didnt load">
{% endblock %}